### ISSUE TITLE
Check GLPK as an alternative to lp_solve

### ISSUE THREAD

**Issue by shellshocked2003** [jhkolb/sparkRocks#17]
See if GLPK will be easier to implement cross-platform and whether it's preferable to lp_solve in general

**Comment by jhkolb** [comment]
I checked out GLPK. Unfortunately, you still have to install a native library and then a JNI library to use it. This is true even if we were to add their binding library as a dependency in SBT.

So, it seems like GLPK wouldn't be any better than what we have now.

**Comment by shellshocked2003** [comment]
Ah, okay. That's a pity. Let's just stick with what we have right now then. 

Is there an easy way to install lp_solve on Windows and Mac, similar to what we did for Linux? I think the majority of people initially using this will be Windows users, so we probably need to provide some guidance or scipt to get lp_solve installed.
