### ISSUE TITLE
Remove Apache Commons Dependency

### ISSUE THREAD

**Issue by jhkolb** [jhkolb/sparkRocks#34]
We're using the Apache Commons library to simplify hash code logic, but it's possible that some of the features of the `Objects` library in Java 7 will suffice.

**Comment by shellshocked2003** [comment]
What kind of impact will this have on our code? Is Apache Commons pretty heavy?

**Comment by jhkolb** [comment]
It's fairly heavy, and we're only using it for one specific thing that I've learned we can do with standard Java/Scala anyways. So it seems kind of silly to keep it around.

It will only affect a couple of `hashCode` methods, so it's not a big thing.

**Comment by shellshocked2003** [comment]
Cool. That seems reasonable.

**Comment by jhkolb** [comment]
Well, I was wrong. It looks like the Apache commons hash code library does a lot to make things "just work", even with Scala rather than Java.

I encountered lots of problems when I tried to use Java's built in `Objects` library. First of all, I had to jump through a bunch of hoops to convert Scala primitives to boxed Java primitives. Even after all that, a lot of our unit tests failed because collections that rely on hashing stopped working properly.

Plus, it looks like we wouldn't actually eliminate the Apache commons library as a dependency anyways. When I removed it from our SBT file, it was still available for import, which makes me think one of our other libraries already requires it.

Given that removing the explicit dependency won't actually do anything, and because avoiding the hash code libraries looks like it will be a pain, I'm inclined so say we should just keep our `hashCode` methods as they are now,

Any thoughts?

**Comment by shellshocked2003** [comment]
I'd say it seems like a good idea to just keep our `hashCode` methods as they are. If other libraries are already pulling it in, I think trying to go through each one and removing its dependency is a lot of unnecessary work. 
The only issue with using it is that it's rather heavy? This only impacts the size of the assembly, right?

**Comment by jhkolb** [comment]
Yeah, let's leave things as they are then.
