### ISSUE TITLE
More Intelligent Ordering When Checking for Blocks to Merge

### ISSUE THREAD

**Issue by jhkolb** [jhkolb/sparkRocks#35]
In `LoadBalancer.removeCommonProcessorJoint`, we should iterate through potential mate blocks in an intelligent order, probably by distance from some point in the plane of the processor joint.

**Comment by shellshocked2003** [comment]
Most likely this will no longer be necessary based new load balancing logic.

**Comment by shellshocked2003** [comment]
This issue is no longer of concern. Addressed in #37.
