### ISSUE TITLE
Remove rockProcessor submodule?

### ISSUE THREAD

**Issue by jhkolb** [jhkolb/sparkRocks#39]
With our new approach that uses joint sets directly, can we remove the rockProcessor Python submodule from our repository? That would nicely simplify things.

**Comment by shellshocked2003** [comment]
Unfortunately, we still need this module. It converts the output to VTK so we can view it in Paraview. I remember when we first looked at this, we thought the VTK libraries were a bit heavy so decided to use the lightweight implementation available in Python (`pyevtk`). I can take another look at what it would take to get VTK into Scala? I think it'll end up being pretty similar to how we dealt with `lp_solve`.

**Comment by jhkolb** [comment]
Ah okay. Let's keep the Python code then. Setting up `lp_solve` was a pain, and I'm actually wondering how well it will play with EC2 when we set things up there.

**Comment by shellshocked2003** [comment]
Yeah, we'll see soon enough. I think by doing the assembly though, it should be pretty straightforward, no?
